### PR TITLE
Docker Support - Tutorial

### PR DESCRIPTION
**Pull request by msfidelis**

### CODE REVIEW

**Comment by msfidelis** [comment]
[Docker para desenvolvedores](https://trello.com/c/rhmJz4w4/540-docker-para-desenvolvedores)

**Comment by msfidelis** [comment]
Approved

**Comment by jhoncf** [comment]
Approved

**Comment by adenilsonoliveira** [comment]
Approved

**Comment by luiscera** [comment]
Approved

**Pull request merged**
